[project]
name = "aebbycellcount"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=10.0.0",
    "numpy>=1.24.0",
    "scipy>=1.11.0",
]
